services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: productservice
      POSTGRES_USER: product_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  productservice:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/productservice
      SPRING_DATASOURCE_USERNAME: product_user
      SPRING_DATASOURCE_PASSWORD: secret
    depends_on:
      - db

volumes:
  dbdata:
