spring:
  datasource:
    url: jdbc:postgresql://db:5432/productservice
    username: product_user
    password: secret
  spring:
    jpa:
      hibernate:
        ddl-auto: update
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
