spring:
  datasource:
    url: jdbc:postgresql://db:5432/products
    username: product_user
    password: secret
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info
